#!/bin/sh


echo "SET NAMES UTF8;" > dump/kladr.sql
tables=`sqlite3 kladr.sqlite3 .tables`
for table in $tables ; do
	echo "DROP TABLE IF EXISTS $table;" >> dump/kladr.sql
	sqlite3 kladr.sqlite3 ".schema $table" | sed 's/autoincrement/auto_increment/'  >> dump/kladr.sql
	[ ! -e dump/$table.csv ] && (sqlite3 -csv kladr.sqlite3 "select * from $table;" | sed "s/\"/'/" > dump/$table.csv)
	echo "LOAD DATA INFILE '`pwd`/dump/$table.csv' INTO TABLE $table CHARACTER SET UTF8 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '\'';" >> dump/kladr.sql
done

echo "CREATE INDEX areas_region_index ON areas (region_code);" >> dump/kladr.sql
echo "CREATE INDEX areas_district_index ON areas (district_code);" >> dump/kladr.sql
echo "CREATE INDEX areas_city_index ON areas (city_code);" >> dump/kladr.sql
echo "CREATE INDEX areas_town_index ON areas (town_code);" >> dump/kladr.sql

#sqlite3 kladr.sqlite3 .dump | grep -v "BEGIN TRANSACTION" |grep -v sqlite_sequence | grep -v COMMIT | perl -pe 's/INSERT INTO "(.*)" VALUES/INSERT INTO `\1` VALUES/' > kladr.sql

